### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/postgresql#1]
package: docbook-utils-0.6.14-42.module_79840da4.noarch from repoclosure-Server.x86_64
  unresolved deps: 
     docbook-style-dsssl >= 0:1.72

package: docbook-utils-pdf-0.6.14-42.module_79840da4.noarch from repoclosure-Server.x86_64
  unresolved deps: 
     jadetex >= 0:2.5
     tex(dvips)
     texlive-collection-fontsrecommended
     texlive-collection-htmlxml

**Comment by nphilipp** [comment]
Thanks for the report, `docbook-utils` and related packages have been moved to the `common-build-dependencies` so I'll rebuild the module with these removed.

**Comment by r4f4** [comment]
Commenting here because I don't know if it's that important. postgresql includes `lynx` which is already part of shared-userspace.
