### ISSUE TITLE
Missing necessary client component: python-psycopg2

### ISSUE THREAD

**Issue by sgallagher** [modularity-modules/postgresql#3]
@whitel 
The postgresql module should include the necessary client tools for interacting with it including (but not limited to) python-psycopg2.

**Comment by nphilipp** [comment]
[Here's how to fix issues like this.](https://docs.pagure.org/modularity/development/building-modules/installation-dependency-issues.html)

**Comment by sgallagher** [comment]
@nphilipp This is kind of a special-case, because this is not a dependency for running the server; it's a client for interacting with a running server.

**Comment by alexxa** [comment]
@sgallagher what is the status of this issue? if it's still valid, should we move it to fedora-modular-release BZ maybe as we report issue there since it was requested so.

**Comment by sgallagher** [comment]
@alexxa I fixed this and forgot to close this issue.

Fixed by https://src.fedoraproject.org/modules/postgresql/c/e73b6b8fbf08270ddd09319140e6df249b4069fb?branch=9.6

**Comment by nphilipp** [comment]
@sgallagher heh sorry for the noise, I just brainlessly added that links to all open install deps issues I could find...
